type: google.api.Service
config_version: 3

name: ${GATEWAY_SVC_NAME}-${PROJ_HASH}-ew.a.run.app

title: The Foo Bar
apis:
  - name: hayovanloon.greeter.v1.Greeter
  - name: hayovanloon.bartender.v1.Bartender

usage:
  rules:
    - selector: "*"
      allow_unregistered_calls: true

backend:
  rules:
    - selector: hayovanloon.greeter.*
      address: grpcs://${BACKEND_SVC_1_NAME}-${PROJ_HASH}-ew.a.run.app
    - selector:  hayovanloon.bartender.*
      address: grpcs://${BACKEND_SVC_2_NAME}-${PROJ_HASH}-ew.a.run.app
