type: google.api.Service
config_version: 3

name: ${GATEWAY_SVC_NAME}-${PROJ_HASH}-ew.a.run.app

title: The Foo Bar
apis:
  - name: hayovanloon.greeter.v1.Greeter
  - name: hayovanloon.bartender.v1.Bartender

authentication:
  providers:
    - id: google_id_token
      issuer: https://accounts.google.com
      audiences: ${CLIENT_ID}
#      jwks_uri: https://www.googleapis.com/oauth2/v3/certs
      authorization_url: https://accounts.google.com
#    - id: google_service_account
#      issuer: ${GATEWAY_SVC_NAME}@${PROJECT}.iam.gserviceaccount.com
#      jwks_uri: https://www.googleapis.com/robot/v1/metadata/x509/${GATEWAY_SVC_NAME}@${PROJECT}.iam.gserviceaccount.com
  rules:
    - selector: "hayovanloon.bartender.*"
      requirements:
        - provider_id: google_id_token
#        - provider_id: google_service_account
    - selector: "hayovanloon.greeter.*"
      requirements:
        - provider_id: google_id_token
#        - provider_id: google_service_account
    - selector: hayovanloon.greeter.v1.Greeter.ListHugs
      requirements: []

backend:
  rules:
    - selector: hayovanloon.greeter.*
      address: grpcs://${BACKEND_SVC_1_NAME}-${PROJ_HASH}-ew.a.run.app
      jwt_audience: "https://${BACKEND_SVC_1_NAME}-${PROJ_HASH}-ew.a.run.app"
    - selector:  hayovanloon.bartender.*
      address: grpcs://${BACKEND_SVC_2_NAME}-${PROJ_HASH}-ew.a.run.app
      jwt_audience: "https://${BACKEND_SVC_2_NAME}-${PROJ_HASH}-ew.a.run.app"
