type: google.api.Service
config_version: 3

name: ${GATEWAY_SVC_NAME}-${PROJ_HASH}-ew.a.run.app

title: Greeter
apis:
  - name: hayovanloon.greeter.Greeter

authentication:
  providers:
    - id: google_service_account
      issuer: ${GATEWAY_SVC_NAME}@${PROJECT}.iam.gserviceaccount.com
      jwks_uri: https://www.googleapis.com/robot/v1/metadata/x509/${GATEWAY_SVC_NAME}@${PROJECT}.iam.gserviceaccount.com
  rules:
    - selector: "*"
      requirements:
        - provider_id: google_service_account

usage:
  rules:
    - selector: "*"
      allow_unregistered_calls: true
#    - selector: "hayovanloon.greeter.Greeter.ListHugs"
#      allow_unregistered_calls: false

backend:
  rules:
    - selector: "*"
      address: grpcs://${BACKEND_SVC_1_NAME}-${PROJ_HASH}-ew.a.run.app
      protocol: h2
      jwt_audience: "${BACKEND_SVC_1_NAME}-${PROJ_HASH}-ew.a.run.app"
      #      disable_auth: true
